# Generated by Django 5.1.2 on 2024-11-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_miscpagecategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiscPageCategories',
        ),
    ]
