# Generated by Django 5.1.2 on 2024-11-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_delete_miscpagecategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscpage',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='miscpage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
