# Generated by Django 5.1.2 on 2024-11-18 07:42

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_miscpage_level_miscpage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miscpage',
            name='level',
        ),
        migrations.RemoveField(
            model_name='miscpage',
            name='name',
        ),
        migrations.AddField(
            model_name='miscpage',
            name='skills',
            field=wagtail.fields.StreamField([('skill', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Skill Name', 'max_length': 50, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Skill Level', 'max_length': 50, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('level', 1)]], {'icon': 'user'})}, help_text='Add multiple skills with their levels.'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='misc.miscpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
