# Generated by Django 5.1.2 on 2024-11-18 09:25

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_remove_miscpage_level_remove_miscpage_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miscpage',
            name='skills',
        ),
        migrations.AlterField(
            model_name='skill',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='misc.miscpage'),
        ),
    ]
