# Generated by Django 5.1.2 on 2024-11-06 08:26

import django.db.models.deletion
import experience.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_alter_experiencepage_body'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencepage',
            name='date_in',
            field=models.IntegerField(blank=True, help_text="Année de début de l'expérience", null=True, validators=[experience.models.validate_year], verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name='experiencepage',
            name='date_out',
            field=models.IntegerField(blank=True, help_text="Année de fin de l'expérience (laisser vide si actuelle)", null=True, validators=[experience.models.validate_year], verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='experiencepage',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Company logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='experiencepage',
            name='summary',
            field=models.TextField(help_text="Résumé de l'expérience", max_length=500),
        ),
    ]
